# Generated by Django 4.2.4 on 2023-08-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_recipe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
